### ISSUE TITLE
尝试使用脚本(ISNET) Multi-frame rendering时出错

### ISSUE THREAD

**Issue by FrogMoD** [ClockZinc/sd-webui-IS-NET-pro#12]
大佬你好，我用你的插件IS net pro的时候，尝试使用脚本(ISNET) Multi-frame rendering时，各种地方已经设置好的时候开始出图会强行停止然后显示：TypeError: Script.run() missing 23 required positional arguments: 'append_interrogation', 'input_dir', 'output_dir', 'first_denoise', 'third_frame_image', 'color_correction_enabled', 'unfreeze_seed', 'loopback_source', 'use_csv', 'table_content', 'use_txt', 'txt_path', 'single_mode_checkbox', 'org_alpha', 'mask_mode_checkbox', 'reverse_checkbox', 'IS_recstrth', 'mask_dir', 'path_name_match_checkbox', 'using_ctrl_net_inpaint_checkbox', 'change_controlnet_image_checkbox', 'ctrlnet_inpaint_unit_num', and 'test_full_inpaint_checkbox'
Time taken: 0.0 sec.
控制台则是： Traceback (most recent call last):
      File "D:\Aki\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "D:\Aki\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\Aki\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\img2img.py", line 230, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "D:\Aki\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\scripts.py", line 501, in run
        processed = script.run(p, *script_args)
    TypeError: Script.run() missing 23 required positional arguments: 'append_interrogation', 'input_dir', 'output_dir', 'first_denoise', 'third_frame_image', 'color_correction_enabled', 'unfreeze_seed', 'loopback_source', 'use_csv', 'table_content', 'use_txt', 'txt_path', 'single_mode_checkbox', 'org_alpha', 'mask_mode_checkbox', 'reverse_checkbox', 'IS_recstrth', 'mask_dir', 'path_name_match_checkbox', 'using_ctrl_net_inpaint_checkbox', 'change_controlnet_image_checkbox', 'ctrlnet_inpaint_unit_num', and 'test_full_inpaint_checkbox'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
疑难解答中则是告诉我组件接口不对应，我的web ui是秋叶整合包的最新版1.5.1，插件版本也是最新，是不是有什么文件缺失了？恳求大佬解答。

**Comment by ClockZinc** [comment]
报错显示：无法检测到你脚本中的输入变量，这种情况建议试试别的脚本能不能跑，还有你设置的界面截图我看看

**Comment by ClockZinc** [comment]
还有就是你是单纯的整合包嘛，里面还有一个（batch only）你试试看那个能运行嘛？也是一个单帧脚本

**Comment by JadynAi** [comment]
和其他插件冲突了，stable diffusion webui升级到1.4之后所有脚本都有这个问题，将cn-animation插件删了就好了

**Comment by FrogMoD** [comment]
@ClockZinc batch only会报错 TypeError: Script.run() missing 4 required positional arguments: 'input_dir', 'output_dir', 'inpaint_mask_dir', and 'scale_by'
控制台：Traceback (most recent call last):
      File "D:\Aki\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "D:\Aki\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\Aki\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\img2img.py", line 230, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "D:\Aki\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\scripts.py", line 501, in run
        processed = script.run(p, *script_args)
    TypeError: Script.run() missing 4 required positional arguments: 'input_dir', 'output_dir', 'inpaint_mask_dir', and 'scale_by'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by FrogMoD** [comment]
@JadynAi  我没有这个插件...

**Comment by JadynAi** [comment]
> @JadynAi 我没有这个插件...

1.4 tagger这个插件的最新版本也会导致这个问题，反正插件库里检查一下，要么就把webui版本回退

**Comment by FrogMoD** [comment]
@

> > @JadynAi 我没有这个插件...
> 
> 1.4 tagger这个插件的最新版本也会导致这个问题，反正插件库里检查一下，要么就把webui版本回退

把tagger版本回退依旧存在问题，我试下回退webui

**Comment by yxcm** [comment]
@FrogMoD  请问您解决了吗

**Comment by dch1314** [comment]
把mov2mov取消了就好了
