### ISSUE TITLE
ValueError: images do not match

### ISSUE THREAD

**Issue by ALANXIAORUI** [ClockZinc/sd-webui-IS-NET-pro#4]
Traceback (most recent call last):
  File "E:\AIdraw\sd-webui-aki-v4\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\AIdraw\sd-webui-aki-v4\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\AIdraw\sd-webui-aki-v4\modules\img2img.py", line 170, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "E:\AIdraw\sd-webui-aki-v4\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "E:\AIdraw\sd-webui-aki-v4\extensions\sd-webui-IS-NET-pro\scripts\multi_frame_rendering.py", line 471, in run
    processed = processing.process_images(p)
  File "E:\AIdraw\sd-webui-aki-v4\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "E:\AIdraw\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "E:\AIdraw\sd-webui-aki-v4\modules\processing.py", line 711, in process_images_inner
    image_mask_composite = Image.composite(image.convert('RGBA').convert('RGBa'), Image.new('RGBa', image.size), p.mask_for_overlay.convert('L')).convert('RGBA')
  File "E:\AIdraw\sd-webui-aki-v4\py310\lib\site-packages\PIL\Image.py", line 3341, in composite
    image.paste(image1, None, mask)
  File "E:\AIdraw\sd-webui-aki-v4\py310\lib\site-packages\PIL\Image.py", line 1731, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by ALANXIAORUI** [comment]
搞定了，要同尺寸

**Comment by Jarcis-cy** [comment]
我将原始图片缩放到了0.7倍，从1920*1080到了1344*756，然后图生图那里也填写了1344*756也没用，还是会报错images do not match。
只有用原图的1920*1080且target的尺寸也是1920*1080才不会报错，感觉这个应该是不符合预期的

**Comment by ClockZinc** [comment]
image not match 主要是因为resize的时候，resize的尺寸和实际的发生了偏差，尺寸貌似得是4或者8的倍数才不会报错。这个是一个老问题了，因为有的时候生成的第一张图片实际上尺寸和设置的并不一样。
