### ISSUE TITLE
自动抠图-生成单图就会出现TypeError：: save_pil_to_file() got an unexpected keyword argument 'format'

### ISSUE THREAD

**Issue by Kireai** [ClockZinc/sd-webui-IS-NET-pro#9]
Traceback (most recent call last):
  File "E:\AIDraw\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AIDraw\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\AIDraw\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\AIDraw\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "E:\AIDraw\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

SD版本是2023年第23周-1.3.2,  Isnet是6月12日新版。

**Comment by Kireai** [comment]
使用批量生成的功能反倒是没有问题

**Comment by ClockZinc** [comment]
貌似是版本不兼容了，先用着批量的吧，这个只是显示不出来，但是你到生成目录找，应该还是有的吧
